name: preflight # You can also change this to another name to avoid warning with existing group.
services:
  backend:
    container_name: pf-backend
    build: .
    ports:
      # - ${PORT}:3772
      - 3772:3772
    networks:
      - preflight_pf-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/app/logs
    # post_start:
    #   - command:
    #       [
    #         "sh",
    #         "-c",
    #         'npm run db:migrate | awk ''{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0; fflush(); }'' | tee -a /app/logs/migration.log',
    #       ]
networks:
  preflight_pf-net: # Check by using `docker network ls` command
    external: true